#!/usr/bin/env bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

# script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

setup_colors

CLI_NAME="csctl"
REPO_NAME="urbanisierung/csctl"

TARGET_DIR="/usr/local/bin"
if [ -w "$TARGET_DIR" ]; then
  TARGET_DIR="/usr/local/bin"
elif [ -w "$HOME/.local/bin" ]; then
  TARGET_DIR="$HOME/.local/bin"
else
  msg "${RED}No writeable bin directory found. Creating $HOME/.local/bin${NOFORMAT}"
  mkdir -p "$HOME/.local/bin"
  msg "${YELLOW}Add $HOME/.local/bin to your PATH in bashrc, zshrc or your preferred shell!${NOFORMAT}"
  TARGET_DIR="$HOME/.local/bin"
  PATH="$PATH:$HOME/.local/bin"
fi

msg "${YELLOW}Installing $CLI_NAME cli... ${NOFORMAT}"
curl https://raw.githubusercontent.com/$REPO_NAME/main/scripts/$CLI_NAME -o $TARGET_DIR/$CLI_NAME
chmod +x $TARGET_DIR/$CLI_NAME

msg "${GREEN}$CLI_NAME cli installed successfully! ${NOFORMAT}"
msg "${YELLOW}Try it out with:${NOFORMAT}"
msg "${YELLOW}$CLI_NAME -h${NOFORMAT}"
